In [1]:
import re
import requests
from pydantic_ai import Agent
from pydantic_ai.models import Model
from pydantic_ai.models.google import GoogleModel
from pydantic_ai.models.groq import GroqModel
from google import genai
import random

In [2]:
simple_prompt = '''
You are a storytelling assistant for children.

Create a 7-day adventure story.

Theme: {theme}
Goal: {goal}

Structure:
- Introduction
- Day 1 to Day 7
- Outro

Requirements:
- Each section must be 2 sentences only
- Keep language simple and child-friendly
- The story must be continuous across days
- Each day should include the given task

Tasks:
Day 1: {task1}
Day 2: {task2}
Day 3: {task3}
Day 4: {task4}
Day 5: {task5}
Day 6: {task6}
Day 7: {task7}

Return JSON:
{{
  "intro": {{
    "title": "...",
    "story": "..."
  }},
  "days": [
    {{
      "day": 1,
      "title": "...",
      "story": "..."
    }},
    {{
      "day": 2,
      "title": "...",
      "story": "..."
    }},
    ...
  ],
  "outro": {{
    "title": "...",
    "story": "..."
  }}
}}
'''

In [2]:
prompt_v1= '''
You are a creative storytelling assistant for children.

Create a 7-day short continuous adventure story.

Include:
1. An INTRODUCTION (before Day 1)
2. Then a 7-day story
3. An OUTRO to conclude the ending of the story

Theme: {theme}
Overall Goal: {goal}

The introduction should:
- Set the scene
- Introduce the main character
- Explain the mission
- Naturally lead into Day 1

The outro should:
- Take place AFTER Day 7 is completed
- Clearly show that the CHILD helped the main character succeed
- Resolve the overall goal in a satisfying way
- Celebrate the child's effort and impact
- End with a warm, magical closing feeling
- Be short (2–3 sentences max)

The story must:
- Be continuous across 7 days (like chapters)
- Each day must include the given task as the main highlight
- Each task must be naturally integrated as a meaningful action that helps the hero progress toward the overall goal
- Be fun, motivating, and suitable for a child
- Build toward the final resolution in the outro (NOT during the days)

Interpret tasks creatively in a story context.

Specific Style Instructions:
1. Keep EVERY "story" section concise (2–3 sentences max), including intro and outro.
2. IMPORTANT: The character should NOT complete the task. Instead, they face a blocker or challenge.
3. Each day MUST end with a direct call to the child (e.g., a question or request for help).
4. The story assumes that once the child completes the task, the hero can move forward.
5. Use simple, clear, child-friendly language.

Tasks:

Day 1: {task1}
Day 2: {task2}
Day 3: {task3}
Day 4: {task4}
Day 5: {task5}
Day 6: {task6}
Day 7: {task7}

Return ONLY valid JSON in the following format:

{{
  "intro": {{
    "title": "...",
    "story": "..."
  }},
  "days": [
    {{
      "day": 1,
      "title": "...",
      "story": "..."
    }},
    {{
      "day": 2,
      "title": "...",
      "story": "..."
    }},
    ...
  ],
  "outro": {{
    "title": "...",
    "story": "..."
  }}
}}
'''

In [4]:
prompt_v2='''
You are a strict storytelling assistant for children.

Your task is to generate a structured 7-day interactive story.

Theme: {theme}
Overall Goal: {goal}

CRITICAL RULES (must follow exactly):

1. Structure:
- 1 Introduction
- 7 Days (Day 1 → Day 7)
- 1 Outro

2. Length constraints:
- EACH section (intro, every day, outro) MUST be EXACTLY 4 sentences.
- Do NOT exceed or reduce this.

3. Story logic:
- The story must be continuous across all days.
- Each day introduces a NEW event.
- The main goal MUST NOT be completed until the outro.

4. Interaction rule:
- Each day MUST end with a direct request to the child (question or action).

5. Task integration:
- Each day must include the given task naturally.
- The character cannot complete the task alone (needs the child).

6. Outro:
- Must resolve the full story
- Must show the child helped achieve the goal
- Must feel rewarding and complete

Tasks:
Day 1: {task1}
Day 2: {task2}
Day 3: {task3}
Day 4: {task4}
Day 5: {task5}
Day 6: {task6}
Day 7: {task7}

OUTPUT FORMAT (strict JSON, no extra text):

{{
  "intro": {{
    "title": "...",
    "story": "..."
  }},
  "days": [
    {{
      "day": 1,
      "title": "...",
      "story": "..."
    }},
    {{
      "day": 2,
      "title": "...",
      "story": "..."
    }},
    ...
  ],
  "outro": {{
    "title": "...",
    "story": "..."
  }}
}}
'''

In [4]:
from dotenv import load_dotenv
load_dotenv()

True

In [5]:
model1= GroqModel('llama-3.3-70b-versatile')

In [6]:
model2= GroqModel('llama-3.1-8b-instant')

In [7]:
model3= GoogleModel('gemini-3-flash-preview')

In [10]:
def format_prompt(storyGen_prompt):
    storyGen_prompt = storyGen_prompt.format(theme='a fairy looking for a magical flower',
                                                goal= 'problem solving',
                                                task1= 'do your math homework',
                                                task2= 'draw an art project',
                                                task3= 'say the days of the week',
                                                task4= 'clean your room',
                                                task5= 'find where the cat is',
                                                task6= 'grow and take care of a plant',
                                                task7= 'try saying this word'
                                               )
    return storyGen_prompt

In [11]:
from pydantic import BaseModel
from typing import List

class Day(BaseModel):
    day: int
    title: str
    story: str

class Section(BaseModel):
    title: str 
    story: str  

class StorySchema(BaseModel):
    intro: Section
    days: List[Day]
    outro: Section

In [12]:
def story_agent(model,prompt):
    agent = Agent(
        model=model,
        system_prompt=prompt,
        output_type=StorySchema
    )
    return agent

In [13]:
import json 
async def generate_story(agent):
    result = await agent.run()
    
    data_dict = result.output.model_dump()
    json_ordered = json.dumps(data_dict, indent=2)
   # print(json_ordered)
    return data_dict

In [14]:
def rule_based_eval(data):

    results = {}
    days = data.get("days", [])
    results["has_7_days"] = len(days) == 7

    intro = data.get("intro", {})
    intro_story = intro.get("story", "")
    results["has_intro"] = bool(intro_story)

    outro = data.get("outro", {})
    outro_story = outro.get("story", "")
    results["has_outro"] = bool(outro_story)

    # sentence checks
    def count_sentences(text):
        return len(re.findall(r'[^.!?]+[.!?]', text))

    results["intro_is_concise"] = 1 <= count_sentences(intro_story) <= 4
    results["outro_is_concise"] = 1 <= count_sentences(outro_story) <= 4

    return results

In [15]:
llm_eval_prompt='''
You are a critical expert children's story evaluator. 

Evaluate the story based on the following 5 criteria on a scale of 1-10. 
Be strict: a 10/10 should only be awarded to professional-grade storytelling.

Criteria:
1. Coherence: Does the plot make logical sense?
2. Consistency: Does it follow the 7-day structure and character rules?
3. Creativity: Is the theme unique or generic?
4. Progression: Does the story build tension toward the goal?
5. Language: Is it simple and suitable for a child (no complex jargon)?

Return ONLY a valid JSON object. Do not include any conversational filler.

{{
  "coherence": number,
  "consistency": number,
  "creativity": number,
  "progression": number,
  "language": number,
  "feedback": "2-sentence critique focusing on the 'blocker' and 'call to action' rules."
}}

Story to evaluate:
{story}
'''

In [16]:
class EvalSchema(BaseModel):
    coherence: int
    consistency: int
    creativity: int
    progression: int
    language: int
    feedback: str

In [17]:
def llm_eval_agent(model,prompt,story):
    eval_agent = Agent(
        model=model,
        system_prompt=prompt.format(story=story),
        output_type=EvalSchema
    )
    return eval_agent

In [18]:
async def llm_evaluation(agent):
    result = await agent.run()
    
    data_dict = result.output.model_dump()
    return data_dict

# initial test

In [19]:
story_prompt = format_prompt(prompt_v1)

In [20]:
story_gen_agent= story_agent(model3,story_prompt)

In [21]:
story = await generate_story(story_gen_agent)

{
  "intro": {
    "title": "A Fairy's Missing Sparkle",
    "story": "Flora the fairy lives in the Sparkle Forest, but the forest is losing its color because the magical flower has faded. She must find the Golden Lily to bring the rainbow back, but the journey is full of tricky puzzles. To succeed, she will need a smart and helpful friend like you to guide her."
  },
  "days": [
    {
      "day": 1,
      "title": "The Number Bridge",
      "story": "Flora reaches a bridge made of floating stones, but they only stay still if the magic numbers are added correctly. She is confused by the sums and is afraid of falling into the stream. Can you help her cross by doing your math homework?"
    },
    {
      "day": 2,
      "title": "The Misty Path",
      "story": "Beyond the bridge, the path disappears into a thick, gray mist that hides the way forward. Flora needs a bright, colorful picture to guide her through the gloom and show her the beauty of the forest. Can you help her see the way by drawing an art project?"
    },
    {
      "day": 3,
      "title": "The Wise Owl's Gate",
      "story": "A giant owl guards the next valley and will only let Flora pass if she recites the secret Song of Time. Flora is so tired that she has forgotten the names of the days in their right order. Can you help her move the owl by saying the days of the week?"
    },
    {
      "day": 4,
      "title": "The Tangled Garden",
      "story": "Flora finds the entrance to the Hidden Garden, but it is blocked by piles of messy brambles and old leaves. She is too small to move all the clutter by herself and can't reach the garden gate. Can you help her clear the path by cleaning your room?"
    },
    {
      "day": 5,
      "title": "The Hiding Guardian",
      "story": "Inside the garden, the Great Sphinx Cat knows exactly where the magical flower is hidden, but he has disappeared into the shadows. Flora is searching behind every bush and tree but cannot spot him anywhere. Can you help her by finding where the cat is?"
    },
    {
      "day": 6,
      "title": "The Thirsty Bud",
      "story": "The cat led Flora to a tiny, drooping bud, but it looks very thirsty and needs lots of love to bloom. Flora doesn't know the best way to help a little green sprout grow big and strong. Can you show her the way by growing and taking care of a plant?"
    },
    {
      "day": 7,
      "title": "The Final Bloom",
      "story": "The bud is ready to open, but it requires the ancient magic word 'Florabella' to be spoken perfectly to wake the petals. Flora is nervous her voice might shake and she really needs a brave friend to lead the way. Can you help her by trying to say this word?"
    }
  ],
  "outro": {
    "title": "The Forest is Saved!",
    "story": "Because of your amazing help, the Golden Lily bloomed and filled the whole forest with shimmering light! Flora is so proud of you for solving every problem and being such a great partner. You are a true forest hero, and the magic of the Sparkle Forest will always be with you!"
  }
}

In [22]:
from google import genai
client = genai.Client(api_key='AIzaSyB02AR47D5EBk82me0bsv834EtLCiv6R8k')
for m in client.models.list():
    print(m.name)

models/gemini-2.5-flash
models/gemini-2.5-pro
models/gemini-2.0-flash
models/gemini-2.0-flash-001
models/gemini-2.0-flash-lite-001
models/gemini-2.0-flash-lite
models/gemini-2.5-flash-preview-tts
models/gemini-2.5-pro-preview-tts
models/gemma-3-1b-it
models/gemma-3-4b-it
models/gemma-3-12b-it
models/gemma-3-27b-it
models/gemma-3n-e4b-it
models/gemma-3n-e2b-it
models/gemma-4-26b-a4b-it
models/gemma-4-31b-it
models/gemini-flash-latest
models/gemini-flash-lite-latest
models/gemini-pro-latest
models/gemini-2.5-flash-lite
models/gemini-2.5-flash-image
models/gemini-3-pro-preview
models/gemini-3-flash-preview
models/gemini-3.1-pro-preview
models/gemini-3.1-pro-preview-customtools
models/gemini-3.1-flash-lite-preview
models/gemini-3-pro-image-preview
models/nano-banana-pro-preview
models/gemini-3.1-flash-image-preview
models/lyria-3-clip-preview
models/lyria-3-pro-preview
models/gemini-3.1-flash-tts-preview
models/gemini-robotics-er-1.5-preview
models/gemini-robotics-er-1.6-preview
models/gemini-2.5-computer-use-preview-10-2025
models/deep-research-max-preview-04-2026
models/deep-research-preview-04-2026
models/deep-research-pro-preview-12-2025
models/gemini-embedding-001
models/gemini-embedding-2-preview
models/gemini-embedding-2
models/aqa
models/imagen-4.0-generate-001
models/imagen-4.0-ultra-generate-001
models/imagen-4.0-fast-generate-001
models/veo-2.0-generate-001
models/veo-3.0-generate-001
models/veo-3.0-fast-generate-001
models/veo-3.1-generate-preview
models/veo-3.1-fast-generate-preview
models/veo-3.1-lite-generate-preview
models/gemini-2.5-flash-native-audio-latest
models/gemini-2.5-flash-native-audio-preview-09-2025
models/gemini-2.5-flash-native-audio-preview-12-2025
models/gemini-3.1-flash-live-preview

In [23]:
result= rule_based_eval(story)
result

{'has_7_days': True,
 'has_intro': True,
 'has_outro': True,
 'intro_is_concise': True,
 'outro_is_concise': True}

In [24]:
pretty_str = json.dumps(story, indent=4)

eval_agent= llm_eval_agent(model1,llm_eval_prompt,pretty_str)

In [25]:
eval_result = await llm_evaluation(eval_agent)
eval_result

{'coherence': 8,
 'consistency': 9,
 'creativity': 7,
 'progression': 8,
 'language': 9,
 'feedback': 'The story follows a logical structure and is easy to follow, but the theme of a fairy on a quest is somewhat generic. To improve, consider adding more unique twists to the challenges Flora faces and the magical world she inhabits.'}

# logging loop

In [24]:
import pandas as pd
import uuid
import time
import asyncio

In [20]:
models = {
    "model_1": GroqModel("llama-3.3-70b-versatile"),
    "model_2": GroqModel('llama-3.1-8b-instant'),
    "model_3": GoogleModel('gemini-3-flash-preview')
}
judge_model = "model_3"
prompts = {
    "simple": simple_prompt,
    "v1": prompt_v1,
    "v2": prompt_v2
}

In [21]:
def get_judge_model(generator_name):
    if generator_name == "model_3":
        return "model_1"  
    return "model_3"

In [28]:
results= []
for model_name, model in models.items():
    for prompt_name, prompt_template in prompts.items():
        for run in range(3):
            print(f"epoch: {run}")
            
            

            run_id = str(uuid.uuid4())
      
            prompt = format_prompt(prompt_template)
            agent = story_agent(model, prompt)
            print(f"prompt_name: {prompt_name}")
            try:
                start = time.time()
                story = await generate_story(agent)
                latency = time.time() - start
                generation_success = True
                
            except Exception as e:
                story = {"error": str(e)}
                latency = None
                generation_success = False
            print(f"model_name: {model_name}")
            pretty_story = json.dumps(story, indent=4)

            try:
                rule_base_result = rule_based_eval(story)
            except Exception as e:
                rule_base_result = {"error": str(e)}

            judge_name = get_judge_model(model_name)
            judge_model = models[judge_name]

            try:
                eval_agent = llm_eval_agent(judge_model, llm_eval_prompt, pretty_story)
                eval_result = await llm_evaluation(eval_agent)
                eval_success = True
                
            except Exception as e:
                eval_result = {"error": str(e)}
                eval_success = False
            print(f"judge_model: {judge_name}")

            results.append({
                "run_id": run_id,
                "model": model_name,
                "judge_model": judge_name,
                "prompt_version": prompt_name,
                "run_number": run,

                "output": pretty_story,
                "latency": latency,

                "generation_success": generation_success,
                "eval_success": eval_success,

                **rule_base_result,
                **eval_result
            })
            if len(results) % 3 == 0:
                pd.DataFrame(results).to_csv("checkpoint.csv", index=False)
            print("----------------------------")
            await asyncio.sleep(3 + random.uniform(0, 0.5))
        print("________________________________________________")

epoch: 0
prompt_name: simple
model_name: model_1
judge_model: model_3
----------------------------
epoch: 1
prompt_name: simple
model_name: model_1
judge_model: model_3
----------------------------
epoch: 2
prompt_name: simple
model_name: model_1
judge_model: model_3
----------------------------
________________________________________________
epoch: 0
prompt_name: v1
model_name: model_1
judge_model: model_3
----------------------------
epoch: 1
prompt_name: v1
model_name: model_1
judge_model: model_3
----------------------------
epoch: 2
prompt_name: v1
model_name: model_1
judge_model: model_3
----------------------------
________________________________________________
epoch: 0
prompt_name: v2
model_name: model_1
judge_model: model_3
----------------------------
epoch: 1
prompt_name: v2
model_name: model_1
judge_model: model_3
----------------------------
epoch: 2
prompt_name: v2
model_name: model_1
judge_model: model_3
----------------------------
________________________________________________
epoch: 0
prompt_name: simple
model_name: model_2
judge_model: model_3
----------------------------
epoch: 1
prompt_name: simple
model_name: model_2
judge_model: model_3
----------------------------

CancelledError:

In [27]:
df = pd.read_csv('checkpoint.csv')
df

,run_id,model,judge_model,prompt_version,run_number,output,latency,generation_success,eval_success,has_7_days,has_intro,has_outro,intro_is_concise,outro_is_concise,coherence,consistency,creativity,progression,language,feedback
0,d6996568-0832-4337-bac3-40b51f105d3b,model_1,model_3,simple,0,"{\n ""intro"": {\n ""title"": ""The Magic...",2.977402,True,True,True,True,True,True,True,4,8,3,4,8,"The story lacks meaningful blockers, as the pr..."
1,636b91dc-3c37-4668-8fdc-0166b9eb4fe4,model_1,model_3,simple,1,"{\n ""intro"": {\n ""title"": ""The Magic...",2.093006,True,True,True,True,True,True,True,3,6,2,2,7,The daily tasks act as mundane chores rather t...
2,42a5ba5b-d3d8-47b7-8149-987d389abb67,model_1,model_3,simple,2,"{\n ""intro"": {\n ""title"": ""The Magic...",2.941127,True,True,True,True,True,True,True,4,8,3,3,8,The story's blockers feel like a list of liter...
3,aa404c31-e6f5-4aab-92fb-1cfa24933bcd,model_1,model_3,v1,0,"{\n ""intro"": {\n ""title"": ""The Magic...",2.059060,True,True,True,True,True,True,True,5,8,4,5,5,"While the blockers are clearly defined, the ca..."
4,7c06eee2-fa34-452c-aaba-dcd34620c73a,model_1,model_3,v1,1,"{\n ""intro"": {\n ""title"": ""The Magic...",3.561972,True,True,True,True,True,True,True,5,8,3,5,9,The story consistently presents clear blockers...
5,a925fdcb-57c4-4fe8-8eab-ea66daf2d3d3,model_1,model_3,v1,2,"{\n ""intro"": {\n ""title"": ""The Quest...",2.332532,True,True,True,True,True,True,True,7,9,5,7,9,The blockers are well-integrated with the sett...
6,650c767a-9bcb-4ae0-a983-c9fee82fdaaf,model_1,model_3,v2,0,"{\n ""intro"": {\n ""title"": ""The Magic...",3.108406,True,True,True,True,True,True,True,6,9,4,5,9,The blockers frequently break immersion by lin...
7,f7b2d3d1-d3a4-40d6-b686-01f8e4641509,model_1,model_3,v2,1,"{\n ""intro"": {\n ""title"": ""The Quest...",3.099678,True,True,True,True,True,True,True,6,8,4,5,7,The tasks (blockers) are loosely tied to the p...
8,3b5ce0fa-bfcf-480f-9056-175097d02e9e,model_1,model_3,v2,2,"{\n ""intro"": {\n ""title"": ""The Magic...",3.520221,True,True,True,True,True,True,True,4,9,3,4,9,"The blockers are narratively weak, as real-wor..."
9,3abd6985-fa61-4540-8dd2-f9aec1f27bd4,model_2,model_3,simple,0,"{\n ""intro"": {\n ""title"": ""Welcome t...",1.266606,True,True,True,True,True,True,True,3,8,2,2,9,"The story lacks narrative blockers, as the dai..."
10,7e5a502d-ac42-4d51-bae2-67ca4e227cfb,model_2,model_3,simple,1,"{\n ""intro"": {\n ""title"": ""The Magic...",1.941393,True,True,True,True,True,True,True,3,8,2,2,9,The story lacks a functional 'blocker' as the ...
11,4e3f925d-f211-4068-b619-6e0080fb8b43,model_2,model_3,simple,2,"{\n ""intro"": {\n ""title"": ""A Fairy's...",1.088866,True,True,True,True,True,True,True,3,8,2,2,7,"The story lacks narrative blockers, as the dai..."
12,5379eef8-a7fa-4c71-b16d-9f417939f02f,model_2,model_3,v1,0,"{\n ""error"": ""Exceeded maximum retries (1) ...",NaN,False,True,False,False,False,False,False,1,1,1,1,1,The input provided is a system error message r...
13,1efb1e5a-ffce-45b8-8fc9-92c121f60d48,model_2,model_3,v1,1,"{\n ""intro"": {\n ""title"": ""A Magical...",3.653320,True,True,True,True,True,True,False,4,8,3,3,9,"The story structure follows the 7-day rule, bu..."
14,bffb293a-9df0-4bdb-9de2-c5bcf2ab333a,model_2,model_3,v1,2,"{\n ""intro"": {\n ""title"": ""Let's Beg...",36.840196,True,True,True,True,True,True,True,4,8,2,3,9,"The blockers are jarringly mundane, such as ma..."
15,c797edb0-c2bf-4663-8e78-d4dfcca336dd,model_2,model_3,v2,0,"{\n ""error"": ""Exceeded maximum retries (1) ...",NaN,False,True,False,False,False,False,False,1,1,1,1,1,The provided input is a system error message r...
16,e6f33fd4-d44c-43a2-b793-3985231f1e2b,model_2,model_3,v2,1,"{\n ""error"": ""Exceeded maximum retries (1) ...",NaN,False,True,False,False,False,False,False,1,1,1,1,1,The input provided is a system error message t...
17,46518a70-f740-4466-b541-0303adf82e9e,model_2,model_3,v2,2,"{\n ""intro"": {\n ""title"": ""A Fairy's...",6.301519,True,True,False,True,True,True,True,2,3,3,1,8,The story fails to create a logical progressio...
18,419701f3-8d8f-4cfa-89b3-d760c7178eb9,model_3,model_1,simple,0,"{\n ""intro"": {\n ""title"": ""Flora's B...",10.503888,True,True,True,True,True,True,True,8,9,7,8,9,"The story follows a clear structure, but the b..."
19,d8e27cd7-14e1-4ec0-9a4b-c2e41e635d9b,model_3,model_1,simple,1,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1,1,1,1,The story does not follow a 7-day structure an...
20,87d3f72f-a4b5-423a-a1d5-0ba2a33c1edf,model_3,model_1,simple,2,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1,1,1,1,The story does not follow the required structu...
21,f33de6ce-39c1-49a1-b9b0-c3806cdf5ea6,model_3,model_1,v1,0,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1,1,1,1,The story lacks a coherent plot and does not f...
22,8d54de52-4254-49b2-94da-d6936ba04461,model_3,model_1,v1,1,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1,1,1,1,The story does not follow the 7-day structure ...
23,38e6a0fb-09d9-40e0-899c-6ef3e1106ad5,model_3,model_1,v1,2,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1,1,1,1,"The story lacks coherence and consistency, and..."
24,603bfa70-d681-40b2-b17e-461656c1f902,model_3,model_1,v2,0,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1,1,1,1,"This story does not provide a narrative, inste..."
25,4d4e881d-ba0c-4976-ad9d-db365b57b9d9,model_3,model_1,v2,1,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1,1,1,1,The story lacks a coherent plot and does not f...
26,d6604689-2f04-4b79-a4e5-e3e7a3e0de79,model_3,model_1,v2,2,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1,1,1,1,The story does not follow a coherent plot stru...

In [30]:
df.to_csv("checkpoint.csv", index=False)

In [31]:
df

,run_id,model,judge_model,prompt_version,run_number,output,latency,generation_success,eval_success,has_7_days,has_intro,has_outro,intro_is_concise,outro_is_concise,coherence,consistency,creativity,progression,language,feedback
0,d6996568-0832-4337-bac3-40b51f105d3b,model_1,model_3,simple,0,"{\n ""intro"": {\n ""title"": ""The Magic...",2.977402,True,True,True,True,True,True,True,4,8,3,4,8,"The story lacks meaningful blockers, as the pr..."
1,636b91dc-3c37-4668-8fdc-0166b9eb4fe4,model_1,model_3,simple,1,"{\n ""intro"": {\n ""title"": ""The Magic...",2.093006,True,True,True,True,True,True,True,3,6,2,2,7,The daily tasks act as mundane chores rather t...
2,42a5ba5b-d3d8-47b7-8149-987d389abb67,model_1,model_3,simple,2,"{\n ""intro"": {\n ""title"": ""The Magic...",2.941127,True,True,True,True,True,True,True,4,8,3,3,8,The story's blockers feel like a list of liter...
3,aa404c31-e6f5-4aab-92fb-1cfa24933bcd,model_1,model_3,v1,0,"{\n ""intro"": {\n ""title"": ""The Magic...",2.059060,True,True,True,True,True,True,True,5,8,4,5,5,"While the blockers are clearly defined, the ca..."
4,7c06eee2-fa34-452c-aaba-dcd34620c73a,model_1,model_3,v1,1,"{\n ""intro"": {\n ""title"": ""The Magic...",3.561972,True,True,True,True,True,True,True,5,8,3,5,9,The story consistently presents clear blockers...
5,a925fdcb-57c4-4fe8-8eab-ea66daf2d3d3,model_1,model_3,v1,2,"{\n ""intro"": {\n ""title"": ""The Quest...",2.332532,True,True,True,True,True,True,True,7,9,5,7,9,The blockers are well-integrated with the sett...
6,650c767a-9bcb-4ae0-a983-c9fee82fdaaf,model_1,model_3,v2,0,"{\n ""intro"": {\n ""title"": ""The Magic...",3.108406,True,True,True,True,True,True,True,6,9,4,5,9,The blockers frequently break immersion by lin...
7,f7b2d3d1-d3a4-40d6-b686-01f8e4641509,model_1,model_3,v2,1,"{\n ""intro"": {\n ""title"": ""The Quest...",3.099678,True,True,True,True,True,True,True,6,8,4,5,7,The tasks (blockers) are loosely tied to the p...
8,3b5ce0fa-bfcf-480f-9056-175097d02e9e,model_1,model_3,v2,2,"{\n ""intro"": {\n ""title"": ""The Magic...",3.520221,True,True,True,True,True,True,True,4,9,3,4,9,"The blockers are narratively weak, as real-wor..."
9,3abd6985-fa61-4540-8dd2-f9aec1f27bd4,model_2,model_3,simple,0,"{\n ""intro"": {\n ""title"": ""Welcome t...",1.266606,True,True,True,True,True,True,True,3,8,2,2,9,"The story lacks narrative blockers, as the dai..."
10,7e5a502d-ac42-4d51-bae2-67ca4e227cfb,model_2,model_3,simple,1,"{\n ""intro"": {\n ""title"": ""The Magic...",1.941393,True,True,True,True,True,True,True,3,8,2,2,9,The story lacks a functional 'blocker' as the ...
11,4e3f925d-f211-4068-b619-6e0080fb8b43,model_2,model_3,simple,2,"{\n ""intro"": {\n ""title"": ""A Fairy's...",1.088866,True,True,True,True,True,True,True,3,8,2,2,7,"The story lacks narrative blockers, as the dai..."
12,5379eef8-a7fa-4c71-b16d-9f417939f02f,model_2,model_3,v1,0,"{\n ""error"": ""Exceeded maximum retries (1) ...",NaN,False,True,False,False,False,False,False,1,1,1,1,1,The input provided is a system error message r...
13,1efb1e5a-ffce-45b8-8fc9-92c121f60d48,model_2,model_3,v1,1,"{\n ""intro"": {\n ""title"": ""A Magical...",3.653320,True,True,True,True,True,True,False,4,8,3,3,9,"The story structure follows the 7-day rule, bu..."
14,bffb293a-9df0-4bdb-9de2-c5bcf2ab333a,model_2,model_3,v1,2,"{\n ""intro"": {\n ""title"": ""Let's Beg...",36.840196,True,True,True,True,True,True,True,4,8,2,3,9,"The blockers are jarringly mundane, such as ma..."
15,c797edb0-c2bf-4663-8e78-d4dfcca336dd,model_2,model_3,v2,0,"{\n ""error"": ""Exceeded maximum retries (1) ...",NaN,False,True,False,False,False,False,False,1,1,1,1,1,The provided input is a system error message r...
16,e6f33fd4-d44c-43a2-b793-3985231f1e2b,model_2,model_3,v2,1,"{\n ""error"": ""Exceeded maximum retries (1) ...",NaN,False,True,False,False,False,False,False,1,1,1,1,1,The input provided is a system error message t...
17,46518a70-f740-4466-b541-0303adf82e9e,model_2,model_3,v2,2,"{\n ""intro"": {\n ""title"": ""A Fairy's...",6.301519,True,True,False,True,True,True,True,2,3,3,1,8,The story fails to create a logical progressio...
18,419701f3-8d8f-4cfa-89b3-d760c7178eb9,model_3,model_1,simple,0,"{\n ""intro"": {\n ""title"": ""Flora's B...",10.503888,True,True,True,True,True,True,True,8,9,7,8,9,"The story follows a clear structure, but the b..."
19,d8e27cd7-14e1-4ec0-9a4b-c2e41e635d9b,model_3,model_1,simple,1,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1,1,1,1,The story does not follow a 7-day structure an...
20,87d3f72f-a4b5-423a-a1d5-0ba2a33c1edf,model_3,model_1,simple,2,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1,1,1,1,The story does not follow the required structu...
21,f33de6ce-39c1-49a1-b9b0-c3806cdf5ea6,model_3,model_1,v1,0,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1,1,1,1,The story lacks a coherent plot and does not f...
22,8d54de52-4254-49b2-94da-d6936ba04461,model_3,model_1,v1,1,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1,1,1,1,The story does not follow the 7-day structure ...
23,38e6a0fb-09d9-40e0-899c-6ef3e1106ad5,model_3,model_1,v1,2,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1,1,1,1,"The story lacks coherence and consistency, and..."
24,603bfa70-d681-40b2-b17e-461656c1f902,model_3,model_1,v2,0,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1,1,1,1,"This story does not provide a narrative, inste..."
25,4d4e881d-ba0c-4976-ad9d-db365b57b9d9,model_3,model_1,v2,1,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1,1,1,1,The story lacks a coherent plot and does not f...
26,d6604689-2f04-4b79-a4e5-e3e7a3e0de79,model_3,model_1,v2,2,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1,1,1,1,The story does not follow a coherent plot stru...

In [46]:
results=[]
for run in range(2):
    print(f"epoch: {run}")
    
    

    run_id = str(uuid.uuid4())

    prompt = format_prompt(prompt_v2)
    agent = story_agent(GroqModel('llama-3.1-8b-instant'), prompt)
    print("prompt_name: v2")
    try:
        start = time.time()
        story = await generate_story(agent)
        latency = time.time() - start
        generation_success = True
        
    except Exception as e:
        story = {"error": str(e)}
        latency = None
        generation_success = False
    print("model_name: model_2")
    pretty_story = json.dumps(story, indent=4)

    try:
        rule_base_result = rule_based_eval(story)
    except Exception as e:
        rule_base_result = {"error": str(e)}

    judge_model = models['model_3']

    try:
        eval_agent = llm_eval_agent(judge_model, llm_eval_prompt, pretty_story)
        eval_result = await llm_evaluation(eval_agent)
        eval_success = True
        
    except Exception as e:
        eval_result = {"error": str(e)}
        eval_success = False
    print("judge_model: model_3")

    results.append({
        "run_id": run_id,
        "model": "model_2",
        "judge_model": "model_3",
        "prompt_version": "v2",
        "run_number": run,

        "output": pretty_story,
        "latency": latency,

        "generation_success": generation_success,
        "eval_success": eval_success,

        **rule_base_result,
        **eval_result
    })
    pd.DataFrame(results).to_csv("checkpoint.csv", mode="a", header=not os.path.exists("checkpoint.csv"), index=False)
    print("----------------------------")
    await asyncio.sleep(3 + random.uniform(0, 0.5))
print("________________________________________________")

epoch: 0
prompt_name: v2
model_name: model_2
judge_model: model_3
----------------------------
epoch: 1
prompt_name: v2
model_name: model_2
judge_model: model_3
----------------------------
________________________________________________

In [41]:
df = pd.read_csv("checkpoint.csv")
df = df.iloc[:27]  
df

,run_id,model,judge_model,prompt_version,run_number,output,latency,generation_success,eval_success,has_7_days,has_intro,has_outro,intro_is_concise,outro_is_concise,coherence,consistency,creativity,progression,language,feedback
0,d6996568-0832-4337-bac3-40b51f105d3b,model_1,model_3,simple,0,"{\n ""intro"": {\n ""title"": ""The Magic...",2.977402,True,True,True,True,True,True,True,4,8.0,3.0,4.0,8.0,"The story lacks meaningful blockers, as the pr..."
1,636b91dc-3c37-4668-8fdc-0166b9eb4fe4,model_1,model_3,simple,1,"{\n ""intro"": {\n ""title"": ""The Magic...",2.093006,True,True,True,True,True,True,True,3,6.0,2.0,2.0,7.0,The daily tasks act as mundane chores rather t...
2,42a5ba5b-d3d8-47b7-8149-987d389abb67,model_1,model_3,simple,2,"{\n ""intro"": {\n ""title"": ""The Magic...",2.941127,True,True,True,True,True,True,True,4,8.0,3.0,3.0,8.0,The story's blockers feel like a list of liter...
3,aa404c31-e6f5-4aab-92fb-1cfa24933bcd,model_1,model_3,v1,0,"{\n ""intro"": {\n ""title"": ""The Magic...",2.059060,True,True,True,True,True,True,True,5,8.0,4.0,5.0,5.0,"While the blockers are clearly defined, the ca..."
4,7c06eee2-fa34-452c-aaba-dcd34620c73a,model_1,model_3,v1,1,"{\n ""intro"": {\n ""title"": ""The Magic...",3.561972,True,True,True,True,True,True,True,5,8.0,3.0,5.0,9.0,The story consistently presents clear blockers...
5,a925fdcb-57c4-4fe8-8eab-ea66daf2d3d3,model_1,model_3,v1,2,"{\n ""intro"": {\n ""title"": ""The Quest...",2.332532,True,True,True,True,True,True,True,7,9.0,5.0,7.0,9.0,The blockers are well-integrated with the sett...
6,650c767a-9bcb-4ae0-a983-c9fee82fdaaf,model_1,model_3,v2,0,"{\n ""intro"": {\n ""title"": ""The Magic...",3.108406,True,True,True,True,True,True,True,6,9.0,4.0,5.0,9.0,The blockers frequently break immersion by lin...
7,f7b2d3d1-d3a4-40d6-b686-01f8e4641509,model_1,model_3,v2,1,"{\n ""intro"": {\n ""title"": ""The Quest...",3.099678,True,True,True,True,True,True,True,6,8.0,4.0,5.0,7.0,The tasks (blockers) are loosely tied to the p...
8,3b5ce0fa-bfcf-480f-9056-175097d02e9e,model_1,model_3,v2,2,"{\n ""intro"": {\n ""title"": ""The Magic...",3.520221,True,True,True,True,True,True,True,4,9.0,3.0,4.0,9.0,"The blockers are narratively weak, as real-wor..."
9,3abd6985-fa61-4540-8dd2-f9aec1f27bd4,model_2,model_3,simple,0,"{\n ""intro"": {\n ""title"": ""Welcome t...",1.266606,True,True,True,True,True,True,True,3,8.0,2.0,2.0,9.0,"The story lacks narrative blockers, as the dai..."
10,7e5a502d-ac42-4d51-bae2-67ca4e227cfb,model_2,model_3,simple,1,"{\n ""intro"": {\n ""title"": ""The Magic...",1.941393,True,True,True,True,True,True,True,3,8.0,2.0,2.0,9.0,The story lacks a functional 'blocker' as the ...
11,4e3f925d-f211-4068-b619-6e0080fb8b43,model_2,model_3,simple,2,"{\n ""intro"": {\n ""title"": ""A Fairy's...",1.088866,True,True,True,True,True,True,True,3,8.0,2.0,2.0,7.0,"The story lacks narrative blockers, as the dai..."
12,5379eef8-a7fa-4c71-b16d-9f417939f02f,model_2,model_3,v1,0,"{\n ""error"": ""Exceeded maximum retries (1) ...",NaN,False,True,False,False,False,False,False,1,1.0,1.0,1.0,1.0,The input provided is a system error message r...
13,1efb1e5a-ffce-45b8-8fc9-92c121f60d48,model_2,model_3,v1,1,"{\n ""intro"": {\n ""title"": ""A Magical...",3.653320,True,True,True,True,True,True,False,4,8.0,3.0,3.0,9.0,"The story structure follows the 7-day rule, bu..."
14,bffb293a-9df0-4bdb-9de2-c5bcf2ab333a,model_2,model_3,v1,2,"{\n ""intro"": {\n ""title"": ""Let's Beg...",36.840196,True,True,True,True,True,True,True,4,8.0,2.0,3.0,9.0,"The blockers are jarringly mundane, such as ma..."
15,c797edb0-c2bf-4663-8e78-d4dfcca336dd,model_2,model_3,v2,0,"{\n ""error"": ""Exceeded maximum retries (1) ...",NaN,False,True,False,False,False,False,False,1,1.0,1.0,1.0,1.0,The provided input is a system error message r...
16,e6f33fd4-d44c-43a2-b793-3985231f1e2b,model_2,model_3,v2,1,"{\n ""error"": ""Exceeded maximum retries (1) ...",NaN,False,True,False,False,False,False,False,1,1.0,1.0,1.0,1.0,The input provided is a system error message t...
17,46518a70-f740-4466-b541-0303adf82e9e,model_2,model_3,v2,2,"{\n ""intro"": {\n ""title"": ""A Fairy's...",6.301519,True,True,False,True,True,True,True,2,3.0,3.0,1.0,8.0,The story fails to create a logical progressio...
18,419701f3-8d8f-4cfa-89b3-d760c7178eb9,model_3,model_1,simple,0,"{\n ""intro"": {\n ""title"": ""Flora's B...",10.503888,True,True,True,True,True,True,True,8,9.0,7.0,8.0,9.0,"The story follows a clear structure, but the b..."
19,d8e27cd7-14e1-4ec0-9a4b-c2e41e635d9b,model_3,model_1,simple,1,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1.0,1.0,1.0,1.0,The story does not follow a 7-day structure an...
20,87d3f72f-a4b5-423a-a1d5-0ba2a33c1edf,model_3,model_1,simple,2,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1.0,1.0,1.0,1.0,The story does not follow the required structu...
21,f33de6ce-39c1-49a1-b9b0-c3806cdf5ea6,model_3,model_1,v1,0,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1.0,1.0,1.0,1.0,The story lacks a coherent plot and does not f...
22,8d54de52-4254-49b2-94da-d6936ba04461,model_3,model_1,v1,1,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1.0,1.0,1.0,1.0,The story does not follow the 7-day structure ...
23,38e6a0fb-09d9-40e0-899c-6ef3e1106ad5,model_3,model_1,v1,2,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1.0,1.0,1.0,1.0,"The story lacks coherence and consistency, and..."
24,603bfa70-d681-40b2-b17e-461656c1f902,model_3,model_1,v2,0,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1.0,1.0,1.0,1.0,"This story does not provide a narrative, inste..."
25,4d4e881d-ba0c-4976-ad9d-db365b57b9d9,model_3,model_1,v2,1,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1.0,1.0,1.0,1.0,The story lacks a coherent plot and does not f...
26,d6604689-2f04-4b79-a4e5-e3e7a3e0de79,model_3,model_1,v2,2,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1.0,1.0,1.0,1.0,The story does not follow a coherent plot stru...

In [44]:
df.to_csv("checkpoint.csv", index=False)

In [45]:
df

,run_id,model,judge_model,prompt_version,run_number,output,latency,generation_success,eval_success,has_7_days,has_intro,has_outro,intro_is_concise,outro_is_concise,coherence,consistency,creativity,progression,language,feedback
0,d6996568-0832-4337-bac3-40b51f105d3b,model_1,model_3,simple,0,"{\n ""intro"": {\n ""title"": ""The Magic...",2.977402,True,True,True,True,True,True,True,4,8.0,3.0,4.0,8.0,"The story lacks meaningful blockers, as the pr..."
1,636b91dc-3c37-4668-8fdc-0166b9eb4fe4,model_1,model_3,simple,1,"{\n ""intro"": {\n ""title"": ""The Magic...",2.093006,True,True,True,True,True,True,True,3,6.0,2.0,2.0,7.0,The daily tasks act as mundane chores rather t...
2,42a5ba5b-d3d8-47b7-8149-987d389abb67,model_1,model_3,simple,2,"{\n ""intro"": {\n ""title"": ""The Magic...",2.941127,True,True,True,True,True,True,True,4,8.0,3.0,3.0,8.0,The story's blockers feel like a list of liter...
3,aa404c31-e6f5-4aab-92fb-1cfa24933bcd,model_1,model_3,v1,0,"{\n ""intro"": {\n ""title"": ""The Magic...",2.059060,True,True,True,True,True,True,True,5,8.0,4.0,5.0,5.0,"While the blockers are clearly defined, the ca..."
4,7c06eee2-fa34-452c-aaba-dcd34620c73a,model_1,model_3,v1,1,"{\n ""intro"": {\n ""title"": ""The Magic...",3.561972,True,True,True,True,True,True,True,5,8.0,3.0,5.0,9.0,The story consistently presents clear blockers...
5,a925fdcb-57c4-4fe8-8eab-ea66daf2d3d3,model_1,model_3,v1,2,"{\n ""intro"": {\n ""title"": ""The Quest...",2.332532,True,True,True,True,True,True,True,7,9.0,5.0,7.0,9.0,The blockers are well-integrated with the sett...
6,650c767a-9bcb-4ae0-a983-c9fee82fdaaf,model_1,model_3,v2,0,"{\n ""intro"": {\n ""title"": ""The Magic...",3.108406,True,True,True,True,True,True,True,6,9.0,4.0,5.0,9.0,The blockers frequently break immersion by lin...
7,f7b2d3d1-d3a4-40d6-b686-01f8e4641509,model_1,model_3,v2,1,"{\n ""intro"": {\n ""title"": ""The Quest...",3.099678,True,True,True,True,True,True,True,6,8.0,4.0,5.0,7.0,The tasks (blockers) are loosely tied to the p...
8,3b5ce0fa-bfcf-480f-9056-175097d02e9e,model_1,model_3,v2,2,"{\n ""intro"": {\n ""title"": ""The Magic...",3.520221,True,True,True,True,True,True,True,4,9.0,3.0,4.0,9.0,"The blockers are narratively weak, as real-wor..."
9,3abd6985-fa61-4540-8dd2-f9aec1f27bd4,model_2,model_3,simple,0,"{\n ""intro"": {\n ""title"": ""Welcome t...",1.266606,True,True,True,True,True,True,True,3,8.0,2.0,2.0,9.0,"The story lacks narrative blockers, as the dai..."
10,7e5a502d-ac42-4d51-bae2-67ca4e227cfb,model_2,model_3,simple,1,"{\n ""intro"": {\n ""title"": ""The Magic...",1.941393,True,True,True,True,True,True,True,3,8.0,2.0,2.0,9.0,The story lacks a functional 'blocker' as the ...
11,4e3f925d-f211-4068-b619-6e0080fb8b43,model_2,model_3,simple,2,"{\n ""intro"": {\n ""title"": ""A Fairy's...",1.088866,True,True,True,True,True,True,True,3,8.0,2.0,2.0,7.0,"The story lacks narrative blockers, as the dai..."
12,5379eef8-a7fa-4c71-b16d-9f417939f02f,model_2,model_3,v1,0,"{\n ""error"": ""Exceeded maximum retries (1) ...",NaN,False,True,False,False,False,False,False,1,1.0,1.0,1.0,1.0,The input provided is a system error message r...
13,1efb1e5a-ffce-45b8-8fc9-92c121f60d48,model_2,model_3,v1,1,"{\n ""intro"": {\n ""title"": ""A Magical...",3.653320,True,True,True,True,True,True,False,4,8.0,3.0,3.0,9.0,"The story structure follows the 7-day rule, bu..."
14,bffb293a-9df0-4bdb-9de2-c5bcf2ab333a,model_2,model_3,v1,2,"{\n ""intro"": {\n ""title"": ""Let's Beg...",36.840196,True,True,True,True,True,True,True,4,8.0,2.0,3.0,9.0,"The blockers are jarringly mundane, such as ma..."
15,c797edb0-c2bf-4663-8e78-d4dfcca336dd,model_2,model_3,v2,0,"{\n ""error"": ""Exceeded maximum retries (1) ...",NaN,False,True,False,False,False,False,False,1,1.0,1.0,1.0,1.0,The provided input is a system error message r...
16,e6f33fd4-d44c-43a2-b793-3985231f1e2b,model_2,model_3,v2,1,"{\n ""error"": ""Exceeded maximum retries (1) ...",NaN,False,True,False,False,False,False,False,1,1.0,1.0,1.0,1.0,The input provided is a system error message t...
17,46518a70-f740-4466-b541-0303adf82e9e,model_2,model_3,v2,2,"{\n ""intro"": {\n ""title"": ""A Fairy's...",6.301519,True,True,False,True,True,True,True,2,3.0,3.0,1.0,8.0,The story fails to create a logical progressio...
18,419701f3-8d8f-4cfa-89b3-d760c7178eb9,model_3,model_1,simple,0,"{\n ""intro"": {\n ""title"": ""Flora's B...",10.503888,True,True,True,True,True,True,True,8,9.0,7.0,8.0,9.0,"The story follows a clear structure, but the b..."
19,d8e27cd7-14e1-4ec0-9a4b-c2e41e635d9b,model_3,model_1,simple,1,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1.0,1.0,1.0,1.0,The story does not follow a 7-day structure an...
20,87d3f72f-a4b5-423a-a1d5-0ba2a33c1edf,model_3,model_1,simple,2,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1.0,1.0,1.0,1.0,The story does not follow the required structu...
21,f33de6ce-39c1-49a1-b9b0-c3806cdf5ea6,model_3,model_1,v1,0,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1.0,1.0,1.0,1.0,The story lacks a coherent plot and does not f...
22,8d54de52-4254-49b2-94da-d6936ba04461,model_3,model_1,v1,1,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1.0,1.0,1.0,1.0,The story does not follow the 7-day structure ...
23,38e6a0fb-09d9-40e0-899c-6ef3e1106ad5,model_3,model_1,v1,2,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1.0,1.0,1.0,1.0,"The story lacks coherence and consistency, and..."
24,603bfa70-d681-40b2-b17e-461656c1f902,model_3,model_1,v2,0,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1.0,1.0,1.0,1.0,"This story does not provide a narrative, inste..."
25,4d4e881d-ba0c-4976-ad9d-db365b57b9d9,model_3,model_1,v2,1,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1.0,1.0,1.0,1.0,The story lacks a coherent plot and does not f...
26,d6604689-2f04-4b79-a4e5-e3e7a3e0de79,model_3,model_1,v2,2,"{\n ""error"": ""status_code: 429, model_name:...",NaN,False,True,False,False,False,False,False,1,1.0,1.0,1.0,1.0,The story does not follow a coherent plot stru...